"""Arm C library enrichment: the term map, the generated file and its loader (DESIGN.md A68).

The builder writes two reviewed sources under ``data/enrichment/``: a term map (each term as a
library writes it, with its equivalents in the other language, abbreviations and standard
designations) and a glossary supplement with the schema of ``prompts/v1/glossary.yaml``. The
offline generator (``scripts/enrich_library.py``) reads one library and those two sources only,
and writes, per type, usage and row of the library, the ``also`` list of every term matching
the node's own label as a whole phrase after the §6 normaliser. Its output is a pure function
of its inputs: sorted keys, LF line ends, no timestamps. The loader checks a file before a run
renders it; the run is refused unless the file was generated from the library it loads.
"""

import functools
import hashlib
import re
from collections.abc import Iterable, Iterator, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Annotated, Literal, Self

import yaml
from pydantic import (
    AfterValidator,
    BaseModel,
    ConfigDict,
    Field,
    StringConstraints,
    ValidationError,
    field_validator,
    model_validator,
)

from oris_matcher.domain.library import Library
from oris_matcher.domain.normalize import normalize
from oris_matcher.prompts.v1.render import LINE_BREAK_RE, Glossary, GlossaryEntry, load_glossary
from oris_matcher.settings import SHA256_HEX_PATTERN, ConfigError

GENERATOR = "scripts/enrich_library.py"
GENERATOR_VERSION = "1"
ENRICHMENT_OFF = "none"
TEXT_ENCODING = "utf-8"
SOURCE_ENCODING = "utf-8-sig"
YAML_WIDTH = 4096
HEADER = "# Generated by scripts/enrich_library.py (DESIGN.md A68); regenerate, never edit.\n"
REFERENCED_SOURCES = frozenset({"standard"})
NODE_LISTS = ("types", "usages", "subtypes")

TermSource = Literal["library", "standard", "dev_error"]
Sha256Hex = Annotated[str, StringConstraints(pattern=SHA256_HEX_PATTERN)]
NonEmptyStr = Annotated[str, StringConstraints(min_length=1)]


def _one_line(text: str) -> str:
    """Refuse a blank string or one holding a line break; it is rendered on one line."""
    if not text.strip() or LINE_BREAK_RE.search(text):
        raise ValueError(f"{text!r} must be one non-blank line")
    return text


OneLine = Annotated[str, AfterValidator(_one_line)]


class _Closed(BaseModel):
    """Base for the enrichment models: closed and frozen."""

    model_config = ConfigDict(extra="forbid", frozen=True)


class TermMapEntry(_Closed):
    """One term-map entry (A68.1).

    Attributes:
        term: A phrase as one library writes it in a type, usage or subtype.
        lang: The term's language.
        equivalents: Short phrases for the same thing: the other language's terms,
            abbreviations and standard designations; general domain terms, never item text.
        source: Provenance tag.
        ref: The public norm or reference; required for a ``standard`` entry.

    """

    term: OneLine
    lang: Literal["en", "fr"]
    equivalents: tuple[OneLine, ...] = Field(min_length=1)
    source: TermSource
    ref: str = ""

    @model_validator(mode="after")
    def _standard_entries_cite_a_source(self) -> Self:
        """Reject a standard entry with no public reference."""
        if self.source in REFERENCED_SOURCES and not self.ref.strip():
            raise ValueError(f"term {self.term!r} is {self.source} but has no ref")
        return self


class TermMap(_Closed):
    """The term map file."""

    entries: tuple[TermMapEntry, ...]


def canonical_also(values: Iterable[str]) -> tuple[str, ...]:
    """Sort and de-duplicate equivalents as the enrichment file stores them.

    Two values that normalise alike are one; the first in raw order is kept. The list is
    ordered by normalised text, then raw text, as the library orders its labels.

    Args:
        values: Equivalents, in any order.

    Returns:
        The canonical ``also`` list.

    """
    kept: dict[str, str] = {}
    for value in sorted(values):
        kept.setdefault(normalize(value), value)
    return tuple(sorted(kept.values(), key=lambda value: (normalize(value), value)))


def _canonical(also: tuple[str, ...]) -> tuple[str, ...]:
    """Refuse an ``also`` list that is not sorted and de-duplicated by ``canonical_also``."""
    if also != canonical_also(also):
        raise ValueError(f"also list {list(also)} is not sorted and de-duplicated")
    return also


AlsoList = Annotated[tuple[OneLine, ...], AfterValidator(_canonical)]


class TypeNode(_Closed):
    """A type of the library and its equivalents."""

    type: NonEmptyStr
    also: AlsoList = ()


class UsageNode(_Closed):
    """A usage (type and usage) of the library and its equivalents."""

    type: NonEmptyStr
    usage: NonEmptyStr
    also: AlsoList = ()


class SubtypeNode(_Closed):
    """A row (type, usage and subtype, which may be blank) of the library and its equivalents."""

    type: NonEmptyStr
    usage: NonEmptyStr
    subtype: str
    also: AlsoList = ()


class Enrichment(_Closed):
    """The generated enrichment file of one library (A68.2).

    Attributes:
        library_sha256: SHA-256 of the library file it was generated from.
        generator: The generator script.
        generator_version: The generator's version.
        term_map_sha256: SHA-256 of the term map read.
        glossary_supplement_sha256: SHA-256 of the glossary supplement read.
        reviewed_by: Who reviewed the sources; empty when nobody has.
        types: One node per type.
        usages: One node per usage.
        subtypes: One node per row.
        glossary: The supplement's entries, copied in.

    """

    library_sha256: Sha256Hex
    generator: NonEmptyStr
    generator_version: NonEmptyStr
    term_map_sha256: Sha256Hex
    glossary_supplement_sha256: Sha256Hex
    reviewed_by: str
    types: tuple[TypeNode, ...]
    usages: tuple[UsageNode, ...]
    subtypes: tuple[SubtypeNode, ...]
    glossary: tuple[GlossaryEntry, ...] = ()

    @field_validator("reviewed_by")
    @classmethod
    def _reviewer_on_one_line(cls, reviewed_by: str) -> str:
        """Refuse a reviewer field holding a line break."""
        if LINE_BREAK_RE.search(reviewed_by):
            raise ValueError("reviewed_by must be one line")
        return reviewed_by


@dataclass(frozen=True)
class LoadedEnrichment:
    """An enrichment file as a run loads it.

    Attributes:
        path: Where it was read.
        sha256: SHA-256 of its bytes; it enters the prompt version and the manifest.
        content: The validated content.

    """

    path: Path
    sha256: str
    content: Enrichment


@dataclass(frozen=True)
class EnrichmentSources:
    """What the generator reads besides the library.

    Attributes:
        term_map: The term map file's bytes.
        supplement: The glossary supplement file's bytes.
        reviewed_by: Who reviewed the sources, recorded as given.

    """

    term_map: bytes
    supplement: bytes
    reviewed_by: str = ""


def is_enrichment_off(path: Path) -> bool:
    """Tell whether a forced enrichment value is ``none``, which turns enrichment off.

    Args:
        path: The forced value.

    Returns:
        True for ``none``.

    """
    return path.as_posix() == ENRICHMENT_OFF


def _sha256(data: bytes) -> str:
    """Return the SHA-256 hex digest of bytes."""
    return hashlib.sha256(data).hexdigest()


def _yaml(data: bytes, what: str) -> object:
    """Parse YAML bytes, raising ValueError that names what they are."""
    try:
        return yaml.safe_load(data.decode(SOURCE_ENCODING))
    except (UnicodeDecodeError, yaml.YAMLError) as error:
        raise ValueError(f"invalid {what}: {error}") from error


def load_term_map(data: bytes) -> TermMap:
    """Parse and validate a term map.

    Args:
        data: The file's bytes.

    Returns:
        The term map.

    Raises:
        ValueError: The YAML is invalid or an entry breaks the schema.

    """
    parsed = _yaml(data, "term map")
    try:
        return TermMap.model_validate(parsed)
    except ValidationError as error:
        raise ValueError(f"invalid term map: {error}") from error


def load_supplement(data: bytes) -> Glossary:
    """Parse and validate a glossary supplement with the glossary's schema.

    Args:
        data: The file's bytes.

    Returns:
        The supplement.

    Raises:
        ValueError: The YAML is invalid or an entry breaks the glossary schema.

    """
    try:
        return load_glossary(data.decode(SOURCE_ENCODING))
    except UnicodeDecodeError as error:
        raise ValueError(f"invalid glossary supplement: {error}") from error


@functools.cache
def _phrase_pattern(term: str) -> re.Pattern[str]:
    """Compile a normalised term as a whole word or phrase."""
    return re.compile(rf"(?<!\w){re.escape(term)}(?!\w)")


def phrase_occurs(term: str, label: str) -> bool:
    """Tell whether a term occurs in a label as a whole phrase, after the §6 normaliser.

    Args:
        term: A term-map term.
        label: A library type, usage or subtype.

    Returns:
        True when the normalised term is a whole word or phrase of the normalised label.

    """
    needle = normalize(term)
    return bool(needle) and _phrase_pattern(needle).search(normalize(label)) is not None


def label_also(label: str, term_map: TermMap) -> tuple[str, ...]:
    """Return the canonical equivalents of every entry whose term occurs in a label.

    Args:
        label: A node's own label.
        term_map: The term map.

    Returns:
        The node's ``also`` list.

    """
    matching = (entry for entry in term_map.entries if phrase_occurs(entry.term, label))
    return canonical_also(value for entry in matching for value in entry.equivalents)


def library_labels(library: Library) -> frozenset[str]:
    """Return every type, usage and non-blank subtype label of a library.

    Args:
        library: The loaded library.

    Returns:
        The raw labels.

    """
    labels = (
        label
        for row in library.rows
        for label in (row.material_type, row.material_usage, row.material_subtype)
    )
    return frozenset(label for label in labels if normalize(label))


def terms_missing_from(term_map: TermMap, libraries: Sequence[Library]) -> list[str]:
    """Return the terms that occur in no label of any of the libraries (A68.1).

    Args:
        term_map: The term map.
        libraries: The libraries a term may come from.

    Returns:
        The missing terms, in file order.

    """
    labels: set[str] = set()
    for library in libraries:
        labels |= library_labels(library)
    return [
        entry.term
        for entry in term_map.entries
        if not any(phrase_occurs(entry.term, label) for label in labels)
    ]


def _distinct[T](values: Iterable[T]) -> Iterator[T]:
    """Yield values once each, in first-seen order."""
    yield from dict.fromkeys(values)


def _nodes(
    library: Library, term_map: TermMap
) -> tuple[tuple[TypeNode, ...], tuple[UsageNode, ...], tuple[SubtypeNode, ...]]:
    """Build the three node lists in display-code order."""
    rows = library.rows
    types = tuple(
        TypeNode(type=name, also=label_also(name, term_map))
        for name in _distinct(row.material_type for row in rows)
    )
    usages = tuple(
        UsageNode(type=name, usage=usage, also=label_also(usage, term_map))
        for name, usage in _distinct((row.material_type, row.material_usage) for row in rows)
    )
    subtypes = tuple(
        SubtypeNode(
            type=row.material_type,
            usage=row.material_usage,
            subtype=row.material_subtype,
            also=label_also(row.material_subtype, term_map),
        )
        for row in rows
    )
    return types, usages, subtypes


def generate(library: Library, sources: EnrichmentSources) -> Enrichment:
    """Generate a library's enrichment from the term map and the supplement only.

    Args:
        library: The loaded library.
        sources: The term map, the supplement and the reviewer.

    Returns:
        The enrichment.

    Raises:
        ValueError: The term map or the supplement is invalid.

    """
    term_map = load_term_map(sources.term_map)
    supplement = load_supplement(sources.supplement)
    types, usages, subtypes = _nodes(library, term_map)
    return Enrichment(
        library_sha256=library.sha256,
        generator=GENERATOR,
        generator_version=GENERATOR_VERSION,
        term_map_sha256=_sha256(sources.term_map),
        glossary_supplement_sha256=_sha256(sources.supplement),
        reviewed_by=sources.reviewed_by,
        types=types,
        usages=usages,
        subtypes=subtypes,
        glossary=supplement.entries,
    )


def dump_enrichment(enrichment: Enrichment) -> str:
    """Write an enrichment as YAML text: sorted keys, LF line ends, no timestamps.

    Args:
        enrichment: The enrichment.

    Returns:
        The file's text, a header comment first.

    """
    body = yaml.safe_dump(
        enrichment.model_dump(mode="json"),
        sort_keys=True,
        allow_unicode=True,
        default_flow_style=False,
        width=YAML_WIDTH,
    )
    return HEADER + body


def parse_enrichment(data: bytes, path: Path) -> LoadedEnrichment:
    """Parse and validate an enrichment file's bytes.

    Args:
        data: The file's bytes.
        path: Where they were read, for messages and the manifest.

    Returns:
        The loaded enrichment.

    Raises:
        ConfigError: The file is not a valid enrichment.

    """
    try:
        content = Enrichment.model_validate(_yaml(data, "enrichment"))
    except (ValueError, ValidationError) as error:
        raise ConfigError(f"{path.as_posix()}: invalid enrichment ({error})") from error
    return LoadedEnrichment(path=path, sha256=_sha256(data), content=content)


def read_enrichment(path: Path) -> LoadedEnrichment:
    """Read and validate an enrichment file.

    Args:
        path: The file.

    Returns:
        The loaded enrichment.

    Raises:
        ConfigError: The file cannot be read or is not a valid enrichment.

    """
    try:
        data = path.read_bytes()
    except OSError as error:
        raise ConfigError(f"{path.as_posix()}: cannot read the enrichment ({error})") from error
    return parse_enrichment(data, path)


def require_library(enrichment: LoadedEnrichment, library: Library) -> None:
    """Refuse an enrichment generated from another library than the one a run loads (A68.4).

    Args:
        enrichment: The loaded enrichment.
        library: The run's library.

    Raises:
        ConfigError: The library SHA-256 values differ.

    """
    recorded = enrichment.content.library_sha256
    if recorded != library.sha256:
        raise ConfigError(
            f"{enrichment.path.as_posix()} was generated from library {recorded[:12]}, but the "
            f"run loads library {library.sha256[:12]}"
        )


def require_enrichment_sha256(enrichment: LoadedEnrichment, expected: str | None) -> None:
    """Refuse an enrichment whose bytes are not the ones a policy entry certified (A68.4).

    Args:
        enrichment: The loaded enrichment.
        expected: The entry's ``enrichment_sha256``; None checks nothing.

    Raises:
        ConfigError: The SHA-256 values differ.

    """
    if expected is not None and enrichment.sha256 != expected:
        raise ConfigError(
            f"{enrichment.path.as_posix()} has sha256 {enrichment.sha256[:12]}, but the policy "
            f"entry certifies {expected[:12]}"
        )
